import { useState, useCallback } from 'react'
import type { BundleData } from './types/bundle'
import WBSTable from './components/WBSTable'
import RACIMatrix from './components/RACIMatrix'
import RiskBoard from './components/RiskBoard'
import BudgetChart from './components/BudgetChart'

const SAMPLE: BundleData = {
  project_name: "Sample Project",
  wbs: [
    { id: "1.1", name: "Requirements", duration_days: 5, dependencies: [] },
    { id: "1.2", name: "Design", duration_days: 10, dependencies: ["1.1"] },
  ],
  raci: [
    { role: "PM", responsible: "Alice", accountable: "Bob", consulted: "Carol", informed: "Dave" },
  ],
  risks: [
    { description: "Scope creep", probability: "medium", impact: "high", mitigation: "Weekly reviews", owner: "Alice" },
  ],
  budget: {
    items: [
      { name: "Design", estimated_cost: 5000, actual_cost: 0 },
      { name: "Development", estimated_cost: 10000, actual_cost: 0 },
    ],
    total: 15000,
  },
}

export default function App() {
  const [data, setData] = useState<BundleData>(SAMPLE)
  const [rawJson, setRawJson] = useState('')

  const handleFile = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (ev) => {
      const text = String(ev.target?.result || '')
      setRawJson(text)
      try {
        const parsed: BundleData = JSON.parse(text)
        setData(parsed)
      } catch {
        alert('Invalid JSON')
      }
    }
    reader.readAsText(file)
  }, [])

  const handlePaste = useCallback(() => {
    try {
      const parsed: BundleData = JSON.parse(rawJson)
      setData(parsed)
    } catch {
      alert('Invalid JSON')
    }
  }, [rawJson])

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-slate-900 text-white py-6">
        <div className="max-w-6xl mx-auto px-4 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">SMOT-PMANAGER</h1>
            <p className="text-slate-400 text-sm">Export & Delivery Dashboard</p>
          </div>
          <div className="no-print flex items-center gap-4">
            <button
              onClick={() => window.print()}
              className="px-4 py-2 bg-blue-500 hover:bg-blue-600 rounded-lg text-sm font-medium transition-colors"
            >
              Print to PDF
            </button>
          </div>
        </div>
      </header>

      <div className="no-print bg-white border-b border-gray-200">
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex flex-col sm:flex-row gap-4 items-start">
            <label className="flex-1">
              <span className="block text-sm font-medium text-gray-700 mb-1">Load JSON file</span>
              <input
                type="file"
                accept=".json"
                onChange={handleFile}
                className="block w-full text-sm text-gray-600 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
              />
            </label>
            <div className="flex-[2]">
              <span className="block text-sm font-medium text-gray-700 mb-1">Or paste JSON</span>
              <div className="flex gap-2">
                <textarea
                  value={rawJson}
                  onChange={(e) => setRawJson(e.target.value)}
                  placeholder='{"project_name": "...", "wbs": [...]}'
                  className="flex-1 min-h-[80px] p-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
                <button
                  onClick={handlePaste}
                  className="px-4 py-2 bg-slate-900 text-white rounded-lg text-sm font-medium hover:bg-slate-800 transition-colors"
                >
                  Load
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <main className="max-w-6xl mx-auto px-4 py-8 space-y-8">
        <div className="flex items-baseline gap-3">
          <h2 className="text-3xl font-bold text-slate-900">{data.project_name}</h2>
          <span className="text-sm text-gray-500">Project Bundle</span>
        </div>

        <WBSTable tasks={data.wbs} />
        <RACIMatrix entries={data.raci} />
        <RiskBoard risks={data.risks} />
        <BudgetChart budget={data.budget} />
      </main>

      <footer className="border-t border-gray-200 bg-white py-6 mt-12">
        <div className="max-w-6xl mx-auto px-4 text-center text-sm text-gray-500">
          Generated by SMOT-PMANAGER &middot; {new Date().toLocaleDateString()}
        </div>
      </footer>
    </div>
  )
}
